version: '3.7'
services:

  iris:
    build:
      context: .
    volumes:
      - ./:/irisdev/app
    command: 
      - --check-caps false
    ports:
    - 52775:52773
    - 51776:1972
    - 8888:8888

  proxy:
    build:
      context: proxy
      args:
        link: 'iris'
        port: '52773'
    image: proxyiris:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./proxy/CSP.ini:/opt/webgateway/bin/CSP.ini
    - ./proxy/httpd-csp.conf:/usr/local/apache2/conf/extra/httpd-csp.conf

  db:
    image: postgres:12.2
    hostname: db
    environment:
        POSTGRES_DB: DemoData
        POSTGRES_PASSWORD: DemoData
        POSTGRES_USER: DemoData
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "DemoData"]
        interval: 30s
        timeout: 30s
        retries: 3
    ports:
    - 5432:5432
    volumes:
      - ./misc:/docker-entrypoint-initdb.d/
